// UTCL-MFG-DATA_FOUNDATION_PLATEFORM/ProcessOpt/KilnOptimization/UI/src/app/common/searchbar/searchbar.component.ts
import { Component, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-searchbar',
  templateUrl: './searchbar.component.html'
})
export class SearchbarComponent {

  searchValue: string = '';

  @Output() searchChange = new EventEmitter<string>();

  onSearch() {
    this.searchChange.emit(this.searchValue);
  }

}
<div class="w-fit">

  <div class="flex items-center rounded-md px-2  transition-colors duration-300
           bg-[var(--search-bg)]
           !border border-[var(--search-border)]">

    <!-- Search Icon -->
    <span class="material-symbols-outlined mr-2 text-[18px]" style="color: var(--search-placeholder)">
      search
    </span>

    <!-- Input -->
    <input type="text" [(ngModel)]="searchValue" (input)="onSearch()" placeholder="Search..." class="bg-transparent outline-none w-full text-sm text-[var(--text-color)]
             placeholder-[var(--search-placeholder)]" />

  </div>

</div>

// UTCL-MFG-DATA_FOUNDATION_PLATEFORM/Dashboard/UI/src/components/SearchBar/SearchBar.jsx
import { Search } from "lucide-react";

export default function SearchBar() {
    return (
        <div className=" w-fit">
            <div className="flex items-center rounded-md px-2 transition-colors duration-300 bg-[var(--search-bg)] border border-[var(--search-border)] ">

                <Search size={18} className="mr-2" style={{ color: "var(--search-placeholder)" }} />
                <input
                    type="text"
                    placeholder="Search..."
                    className="bg-transparent outline-none w-full placeholder-[var(--search-placeholder)]"
                />

            </div>
        </div>
    );
}
