// UTCL-MFG-DATA_FOUNDATION_PLATEFORM/ProcessOpt/CementOptimization/UI/src/app/common/breadCrumb/breadCrumb.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, NavigationEnd } from '@angular/router';
import { filter } from 'rxjs/operators';

interface CrumbConfig {
  crumbs: string[];
  paths: (string | null)[];
  icon: 'kiln' | 'cogs' | 'default';
}

@Component({
  selector: 'app-breadcrumb',
  templateUrl: './breadCrumb.component.html',
})
export class BreadcrumbComponent implements OnInit {

  currentPath = '';

 routeConfig: Record<string, CrumbConfig> = {
    '/home':                { crumbs: ['Process Optimization', 'Cement OPT', 'Home'],            paths: [null, null, null], icon: 'cogs' },
    '/dashboard':           { crumbs: ['Process Optimization', 'Cement OPT', 'Dashboard'],       paths: [null, null, null], icon: 'cogs' },
    '/recommendationsList': { crumbs: ['Process Optimization', 'Cement OPT', 'Recommendations'], paths: [null, null, null], icon: 'cogs' },
    '/adminpage':           { crumbs: ['Process Optimization', 'Cement OPT', 'Admin'],           paths: [null, null, null], icon: 'cogs' },
};

  current: CrumbConfig | null = null;

  constructor(private router: Router) {}

  ngOnInit(): void {
    this.currentPath = this.getPath();
    this.current = this.routeConfig[this.currentPath] || null;

    this.router.events
      .pipe(filter(e => e instanceof NavigationEnd))
      .subscribe((e: any) => {
        this.currentPath = this.getPath();
        this.current = this.routeConfig[this.currentPath] || null;
      });
  }

  getPath(): string {
    const hash = window.location.hash;
    return hash ? hash.replace('#', '') : this.router.url;
  }

  navigate(path: string | null): void {
    if (path) this.router.navigate([path]);
  }

  isLast(index: number): boolean {
    return index === (this.current?.crumbs.length ?? 0) - 1;
  }
}
<nav aria-label="breadcrumb" class="mb-1" *ngIf="current">
  <ol class="flex items-center gap-2 text-sm">

    <ng-container *ngFor="let crumb of current.crumbs; let i = index">

      <!-- Separator -->
      <span *ngIf="i > 0" class="text-[var(--card-subtle)]">/</span>

      <!-- Clickable crumb -->
      <button
        *ngIf="current.paths[i]; else staticCrumb"
        (click)="current.paths[i] && navigate(current.paths[i])"
        class="flex items-center gap-1 font-medium text-[var(--leftdrawer-text)] hover:text-[var(--card-border)] transition-colors duration-200 focus:outline-none"
      >
        <ng-container *ngIf="i === 0">
          <ng-container *ngTemplateOutlet="iconTpl; context: { $implicit: current.icon }"></ng-container>
        </ng-container>
        {{ crumb }}
      </button>

      <!-- Static crumb -->
      <ng-template #staticCrumb>
        <span
          class="flex items-center gap-1 text-[var(--leftdrawer-text)]"
          [class.font-semibold]="isLast(i)"
          [class.font-medium]="!isLast(i)"
        >
          <ng-container *ngIf="i === 0">
            <ng-container *ngTemplateOutlet="iconTpl; context: { $implicit: current.icon }"></ng-container>
          </ng-container>
          {{ crumb }}
        </span>
      </ng-template>

    </ng-container>
  </ol>
</nav>

<!-- Icon Template -->
<ng-template #iconTpl let-icon>
  <!-- Cogs icon — Process Optimization -->
  <svg *ngIf="icon === 'cogs'" xmlns="http://www.w3.org/2000/svg"
       class="w-[14px] h-[14px] mr-1 shrink-0" fill="currentColor" viewBox="0 0 20 20">
    <path fill-rule="evenodd"
      d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z"
      clip-rule="evenodd" />
  </svg>

  <!-- Default settings icon -->
  <svg *ngIf="icon !== 'cogs'" xmlns="http://www.w3.org/2000/svg"
       class="w-[14px] h-[14px] mr-1 shrink-0" fill="none"
       viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
    <path stroke-linecap="round" stroke-linejoin="round"
      d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
    <circle cx="12" cy="12" r="3" />
  </svg>
</ng-template>

// UTCL-MFG-DATA_FOUNDATION_PLATEFORM/CBM/UI/src/components/BreadCrumb/BreadCrumb.jsx
import { useNavigate, useLocation } from "react-router-dom";
import { HiOutlineWrenchScrewdriver } from "react-icons/hi2";

const BreadCrumb = () => {
    const navigate = useNavigate();
    const location = useLocation();

   const routeConfig = {
    "/":              { crumbs: ["CBM"],                                                                      paths: [null],                    showCreate: false },
    "/templates":         { crumbs: ["CBM", "Equipment Template List"],                                   paths: [null, null],              showCreate: true,  createPath: "/createTemplate" },
    "/createTemplate":    { crumbs: ["CBM", "Equipment Template List", "Equipment Template Configuration"], paths: [null, "/templates", null], showCreate: false },
    "/editTemplate":      { crumbs: ["CBM", "Equipment Template List", "Equipment Template Configuration"], paths: [null, "/templates", null], showCreate: false },
    "/EmailTemplateList": { crumbs: ["CBM", "Email Template List"],                                       paths: [null, null],              showCreate: true,  createPath: "/EmailTemplate" },
    "/EmailTemplate":     { crumbs: ["CBM", "Email Template List", "Email Template"],                     paths: [null, "/EmailTemplateList", null], showCreate: false },
    "/editEmailTemplate": { crumbs: ["CBM", "Email Template List", "Email Template"],                     paths: [null, "/EmailTemplateList", null], showCreate: false },
    "/cyclonelist":       { crumbs: ["CBM", "Cyclone View List"],                                         paths: [null, null],              showCreate: false },
    "/cycloneview":       { crumbs: ["CBM", "Cyclone View List", "Cyclone View"],                         paths: [null, "/cyclonelist", null], showCreate: false },
};

    const current = routeConfig[location.pathname];
    if (!current) return null;

    return (
        <nav aria-label="breadcrumb" className="mb-1">
            <ol className="flex items-center gap-2 text-sm w-full justify-between">

                {/* Left — Breadcrumb */}
                <div className="flex items-center gap-2">
                    {current.crumbs.map((crumb, index) => {
                        const isLast = index === current.crumbs.length - 1;
                        const isFirst = index === 0;
                        const path = current.paths[index];

                        return (
                            <div key={index} className="flex items-center gap-2">
                                {/* Separator */}
                                {index > 0 && (
                                    <span className="text-[var(--card-subtle)]">/</span>
                                )}

                                {/* Clickable crumb */}
                                {path ? (
                                    <button
                                        onClick={() => navigate(path)}
                                        className="flex items-center gap-1 font-medium text-[var(--text-color)] hover:text-[var(--card-border)] transition-colors duration-200 focus:outline-none"
                                    >
                                        {isFirst && <HiOutlineWrenchScrewdriver size={14} className="mr-1" />}
                                        {crumb}
                                    </button>
                                ) : (
                                    /* Non-clickable crumb */
                                    <span className={`flex items-center gap-1 ${isLast ? "font-semibold" : "font-medium"} text-[var(--text-color)]`}>
                                        {isFirst && <HiOutlineWrenchScrewdriver size={14} className="mr-1" />}
                                        {crumb}
                                    </span>
                                )}
                            </div>
                        );
                    })}
                </div>

               
            </ol>
        </nav>
    );
};

export default BreadCrumb;
