// UTCL-MFG-DATA_FOUNDATION_PLATEFORM/Dashboard/UI/src/Admin/Header/header.jsx
// import React from "react";
// import styles from "./header.module.css";
// // import Login from '../../components/login/Login';

// import Logo from "../../img/logo.png";

// const Header = () => {
//   return (
//     <>
//       <header className="tonav">
//         <div className="header__container">
//           <div className="celebal__logo mr-auto">
//             <img src={Logo} alt="" />
//           </div>
//         </div>
//       </header>
//       {/* <Login></Login> */}
//     </>
//   );
// };

// export default Header;





import React from "react";
import Logo from "../../img/adityabirlalogo.png";

const Header = () => {
  return (
    <header className="w-full h-14 bg-[var(--bg-header)] px-6 flex items-center justify-between shadow-[var(--header-shadow)] sticky top-0 z-50">
      <div className="flex items-center gap-3">

        <img
          src={Logo}
          alt="Aditya Birla Logo"
          className="h-10 w-auto object-contain"
        />

        <h1 className="text-sm sm:text-md md:text-lg lg:text-lg xl:text-xl text-[var(--text-color)] font-semibold tracking-tight">
          Prakriti: UltraTech's Unified OT Data Foundation
        </h1>

      </div>
    </header>
  );
};

export default Header;

// UTCL-MFG-DATA_FOUNDATION_PLATEFORM/ProcessOpt/CementOptimization/UI/src/app/common/header/header.component.ts
import { Component } from '@angular/core';
import { MsalService } from '@azure/msal-angular';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
})
export class HeaderComponent {

  logoPath!: string;
  userName: string = '';

  constructor(private authService: MsalService) {}

  ngOnInit() {
    this.logoPath = '../cementBuild/assets/logo.png';

      const loginData = localStorage.getItem('login');
  if (loginData) {
    const user = JSON.parse(loginData);
    this.userName = user.username;   // take username from login object
  }
  }

  logOut() {
    this.authService.logoutPopup({
      mainWindowRedirectUri: "/login"
    });

    localStorage.clear();
    sessionStorage.clear();
  }
}
<div class="w-auto h-14 bg-[var(--bg-header)] px-6 flex items-center justify-between [box-shadow:var(--header-shadow)]">

  <!-- LEFT SIDE -->
  <div class="flex items-center gap-2">
    <img
      src="assets/adityabirlalogo.png"
      alt="Aditya Birla Logo"
      class="w-[51] h-[50px] object-contain"
    />

    <h1 class="text-sm sm:text-base md:text-lg lg:text-lg xl:text-xl
               text-[var(--header-text-color)] title-font font-medium  tracking-tight">
      Prakriti: UltraTech's Unified OT Data Platform
    </h1>
  </div>

  <!-- RIGHT SIDE -->
  <div class="profile flex items-center gap-3">
  <small class="text-[var(--header-text-color)]">
    <b>Welcome</b> {{ userName }}
  </small>

  <a (click)="logOut()" class="cursor-pointer">
    <i class='bx bx-log-out-circle text-[var(--header-text-color)] text-xl rotate-90'></i>
  </a>
</div>

</div>
